### ISSUE TITLE
post install message scrambled in ruby 1.9.3

### ISSUE THREAD

**Issue by grosser** [janlelis/clipboard#10]
Fetching: clipboard-0.9.9.gem (100%)
       âââ info âââââââââââââââââââââââââââââââ
 J-_-L â http://github.com/janlelis/clipboard â
       âââ usage ââââââââââââââââââââââââââââââ¤
       â require 'clipboard'                  â
       â Clipboard.copy '42'                  â
       â Clipboard.paste #=> 42               â
       ââââââââââââââââââââââââââââââââââââââââ

**Comment by janlelis** [comment]
removed with 1.0.6
