### ISSUE TITLE
why don't you make ffi a dependency in the gemspec?

### ISSUE THREAD

**Issue by ghost** [janlelis/clipboard#21]
It would be pretty cool because then it would automatically do it for people.

however you might need a check for only windows but I'm sure that's possible

**Comment by IgorJorobus** [comment]
It could be nice. You can check if on Windows by inspecting ENV like this:

 `if(ENV['OS'].match(/windows/i))`

 Cheers.

**Comment by janlelis** [comment]
Some people had troubles installing `ffi`, so it is not mandatory. But I've added a `Gemfile` example with platform support in the README: https://github.com/janlelis/clipboard#setup
