### ISSUE TITLE
doesn't work well on unicode

### ISSUE THREAD

**Issue by ghost** [janlelis/clipboard#22]
E:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/clipboard-1.0.6/lib/clipboard/windows.rb:54:in `encode': U+FF11 to IBM437 in conversion from UTF-16LE to UTF-8 to IBM437 (Encoding::UndefinedConversionError)
        from E:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/clipboard-1.0.6/lib/clipboard/windows.rb:54:in `paste'
        from E:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/clipboard-1.0.6/lib/clipboard/windows.rb:91:in `copy'
        from E:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/clipboard-1.0.6/lib/clipboard.rb:49:in `copy'
        from E:/Programs/spacify.rb:14:in `<main>'

really stupid fix is at line 54 in windows.rb remove .encode(Encoding.default_external)

**Comment by afffsdd** [comment]
if you're curious i tried to put this on my clipboard: ﻿１２３４

**Comment by RoxasShadow** [comment]
If someone needs a quick fix, just do `Encoding.default_external = 'utf-8'`.

**Comment by janlelis** [comment]
Starting with version 1.1.0, encoding handling is left to the user. Closing this, but feel free to open a new issue if you run into problems with the new approach!
