### ISSUE TITLE
Cannot copy clipboard in linux 16.4

### ISSUE THREAD

**Issue by mpermperpisang** [janlelis/clipboard#30]
Hi, I still cannot use clipboard in my ruby script and linux server
xclip -version
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL

I tried Clipboard.copy("abc") but it does not copy the abc word, I'm using 
gem 'clipboard', '~> 1.1', '>= 1.1.1'

any idea what's wrong? thank u

**Comment by janlelis** [comment]
Hi! Are you using executing the program locally or on the server? If on the server, have you connected to it using the the `ssh -Y` option?

**Comment by janlelis** [comment]
Closing, please post to #34 if it still not works for you
