### ISSUE TITLE
Not copying to clipboard on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by macmartine** [janlelis/clipboard#34]
Hi!

I installed this in a Rails 5 app on Ubuntu:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

irb(main):003:0> puts `xclip -version`.include?('xclip version')
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
false
=> nil
irb(main):004:0> puts `xclip -version`
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL

When I run rails console and try to use the Clipboard, no luck:

irb(main):001:0> Clipboard.copy "mac"
=> ""
irb(main):002:0>  Clipboard.paste
=> ""

Any ideas?

**Comment by macmartine** [comment]
Oh, I don't have the Linux GUI installed -- just the server. That's probably why??

**Comment by janlelis** [comment]
Hi! Are you using executing the program locally or on the server? If on the server, have you connected to it using the the `ssh -Y` option?

Also, can you please post the output of `Clipboard.implementation` (in the Rails console).

**Comment by adsteel** [comment]
I'm having the same issue in a Ruby gem (not Rails) on Ubuntu 18.04.1 LTS.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```


```ruby
Clipboard.implementation
=> Clipboard::File
```

**Comment by janlelis** [comment]
@adsteel Can you please verify that you have **xclip** or **xsel** installed. If so, in which version? (`xsel --version` or `xclip -version`)

**Comment by adsteel** [comment]
Thanks @janlelis. Installing xclip solved it.

**Comment by janlelis** [comment]
@adsteel Great!

@macmartine Closing this issue, but feel free to re-open with the feedback asked in https://github.com/janlelis/clipboard/issues/34#issuecomment-445591561 if the problem persists
