### ISSUE TITLE
Not working on WSL on Windows 10

### ISSUE THREAD

**Issue by khiav223577** [janlelis/clipboard#35]
It works find in cmd, but  doesn't work in bash

### OS version
Microsoft Windows 10.0.17134.441
```
cat /proc/version
// => Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #345-Microsoft Wed Sep 19 17:47:00 PST 2018
```

**Comment by janlelis** [comment]
Thank you for this feature request. I am right now installing ubuntu 18.04 inside windows 10 inside ubuntu 18.04, exciting times...

Should be possible by using the `clip.exe` + `powershell.exe -Command Get-Clipboard` approach from here: https://github.com/Microsoft/WSL/issues/1069

**Comment by janlelis** [comment]
I've just released a version with WSL support.
