### ISSUE TITLE
FrozenError on Windows

### ISSUE THREAD

**Issue by scivola** [janlelis/clipboard#36]
The following script causes FrozenError on Windows at [here](https://github.com/janlelis/clipboard/blob/master/lib/clipboard/windows.rb#L52).

```rb
gem "clipboard", "1.3.1"
require "clipboard"

Clipboard.copy "Foo"
```

The cause is simply [adding `# frozen_string_literal: true`](https://github.com/janlelis/clipboard/commit/39f0a8ded834d96198ca7766204b1d08f95d2352#diff-b76801565a7c51591c040a69f3d49def).

**Comment by scivola** [comment]
This will fix the problem.

```diff
diff --git a/lib/clipboard/windows.rb b/lib/clipboard/windows.rb
index 613468b..6b6e27b 100644
--- a/lib/clipboard/windows.rb
+++ b/lib/clipboard/windows.rb
@@ -42,7 +42,7 @@ module Clipboard
 
     # see http://www.codeproject.com/KB/clipboard/archerclipboard1.aspx
     def paste(_ = nil)
-      data = ""
+      data = +""
       if 0 != User32.open( 0 )
         hclip = User32.get( CF_UNICODETEXT )
         if hclip && 0 != hclip
```

**Comment by janlelis** [comment]
Right! Thanks!

The fix is released!
