### ISSUE TITLE
Update documentation if other TextFormats are supported

### ISSUE THREAD

**Issue by coezbek** [janlelis/clipboard#41]
I couldn't make out from the README if `clipboard` gem supports getting formatting clipboard contents (RTF, HTML, Files, etc) or only text. Looking into the code it seems not (right?).

Could you update the readme to give this as a limitation?

**Comment by janlelis** [comment]
Thanks for bringing this up. I've added a TODO section to the readme: https://github.com/janlelis/clipboard/commit/9c7a7b2881005eecba50ccbe451d082d5861f740
